/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

// This code is auto-generated by Plasmic; please do not edit!
// Plasmic Project: tSVYD7duZSHF8JH3NprF3M

import { createUseGlobalVariants } from "@plasmicapp/react-web";

import { useScreenVariants as useScreenVariantstu1FhEJUim } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: tu1_FhE_JUim/globalVariant

export const _useGlobalVariants = createUseGlobalVariants({
  screen: useScreenVariantstu1FhEJUim
});
