/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: tSVYD7duZSHF8JH3NprF3M
// Component: vrdOk3RRPsdv

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import { _useGlobalVariants } from "./plasmic"; // plasmic-import: tSVYD7duZSHF8JH3NprF3M/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: tSVYD7duZSHF8JH3NprF3M/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic.module.css"; // plasmic-import: tSVYD7duZSHF8JH3NprF3M/projectcss
import sty from "./PlasmicHome.module.css"; // plasmic-import: vrdOk3RRPsdv/css

import Icon29Icon from "./icons/PlasmicIcon__Icon29"; // plasmic-import: OwH2Bistf0rB/icon

const emptyProxy: any = new Proxy(() => "", {
  get(_, prop) {
    return prop === Symbol.toPrimitive ? () => "" : emptyProxy;
  }
});

function wrapQueriesWithLoadingProxy($q: any): any {
  return new Proxy($q, {
    get(target, queryName) {
      const query = target[queryName];
      return !query || query.isLoading || !query.data ? emptyProxy : query;
    }
  });
}

export type PageCtx = {
  pageRoute: string;
  pagePath: string;
  params: Record<string, string | string[] | undefined>;
  query: Record<string, string | string[] | undefined>;
};

export function generateDynamicMetadata($q: any, $ctx: PageCtx) {
  return {
    openGraph: {},
    twitter: {
      card: "summary" as const
    }
  };
}

createPlasmicElementProxy;

export type PlasmicHome__VariantMembers = {};
export type PlasmicHome__VariantsArgs = {};
type VariantPropType = keyof PlasmicHome__VariantsArgs;
export const PlasmicHome__VariantProps = new Array<VariantPropType>();

export type PlasmicHome__ArgsType = {};
type ArgPropType = keyof PlasmicHome__ArgsType;
export const PlasmicHome__ArgProps = new Array<ArgPropType>();

export type PlasmicHome__OverridesType = {
  root?: Flex__<"div">;
  aboutUs?: Flex__<"a"> & Partial<LinkProps>;
  contact?: Flex__<"div">;
  foreground2?: Flex__<"div">;
  h1?: Flex__<"h1">;
  foreground3?: Flex__<"div">;
  rowWrapper?: Flex__<"div">;
  colmn1?: Flex__<"div">;
  colmn2?: Flex__<"div">;
  colmn22?: Flex__<"div">;
  colmn3?: Flex__<"div">;
};

export interface DefaultHomeProps {}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicHome__RenderFunc(props: {
  variants: PlasmicHome__VariantsArgs;
  args: PlasmicHome__ArgsType;
  overrides: PlasmicHome__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const globalVariants = _useGlobalVariants();

  const pageMetadata = generateDynamicMetadata(
    wrapQueriesWithLoadingProxy({}),
    $ctx as PageCtx
  );

  const styleTokensClassNames = _useStyleTokens();

  return (
    <React.Fragment>
      <Head></Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            styleTokensClassNames,
            sty.root
          )}
        >
          <div className={classNames(projectcss.all, sty.freeBox__xyDRl)}>
            <div className={classNames(projectcss.all, sty.freeBox__d0Ein)}>
              <PlasmicLink__
                className={classNames(
                  projectcss.all,
                  projectcss.a,
                  projectcss.a__tSVYD,
                  sty.link___6G2Cy
                )}
                component={Link}
                legacyBehavior={false}
                platform={"nextjs"}
              >
                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img__qeBy9)}
                  displayHeight={"78px"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"78px"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"100%"}
                  src={
                    "/plasmic/beginners_guide_website_in_3_minutes/images/logoSvg.svg"
                  }
                />
              </PlasmicLink__>
              <div className={classNames(projectcss.all, sty.freeBox__xmk9)}>
                <PlasmicLink__
                  data-plasmic-name={"aboutUs"}
                  data-plasmic-override={overrides.aboutUs}
                  className={classNames(
                    projectcss.all,
                    projectcss.a,
                    projectcss.a__tSVYD,
                    sty.aboutUs
                  )}
                  component={Link}
                  legacyBehavior={false}
                  platform={"nextjs"}
                >
                  {false ? (
                    <Icon29Icon
                      className={classNames(projectcss.all, sty.svg__s85R1)}
                      role={"img"}
                    />
                  ) : null}
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__zQ8Go
                    )}
                  >
                    {"About Us"}
                  </div>
                  {false ? (
                    <Icon29Icon
                      className={classNames(projectcss.all, sty.svg__rgnTb)}
                      role={"img"}
                    />
                  ) : null}
                </PlasmicLink__>
                <PlasmicLink__
                  className={classNames(
                    projectcss.all,
                    projectcss.a,
                    projectcss.a__tSVYD,
                    sty.link__jMmCq
                  )}
                  component={Link}
                  legacyBehavior={false}
                  platform={"nextjs"}
                >
                  {false ? (
                    <Icon29Icon
                      className={classNames(projectcss.all, sty.svg__qaJoJ)}
                      role={"img"}
                    />
                  ) : null}
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___4Xp3J
                    )}
                  >
                    {"Services"}
                  </div>
                  {false ? (
                    <Icon29Icon
                      className={classNames(projectcss.all, sty.svg__iCmcd)}
                      role={"img"}
                    />
                  ) : null}
                </PlasmicLink__>
                <PlasmicLink__
                  className={classNames(
                    projectcss.all,
                    projectcss.a,
                    projectcss.a__tSVYD,
                    sty.link__wLdnL
                  )}
                  component={Link}
                  legacyBehavior={false}
                  platform={"nextjs"}
                >
                  {false ? (
                    <Icon29Icon
                      className={classNames(projectcss.all, sty.svg__r8WwP)}
                      role={"img"}
                    />
                  ) : null}
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__ynLq2
                    )}
                  >
                    {"Clients"}
                  </div>
                  {false ? (
                    <Icon29Icon
                      className={classNames(projectcss.all, sty.svg__zgTpy)}
                      role={"img"}
                    />
                  ) : null}
                </PlasmicLink__>
                <PlasmicLink__
                  className={classNames(
                    projectcss.all,
                    projectcss.a,
                    projectcss.a__tSVYD,
                    sty.link__rOz3K
                  )}
                  component={Link}
                  legacyBehavior={false}
                  platform={"nextjs"}
                >
                  {false ? (
                    <Icon29Icon
                      className={classNames(projectcss.all, sty.svg__moKei)}
                      role={"img"}
                    />
                  ) : null}
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__ogB3F
                    )}
                  >
                    {"Blog"}
                  </div>
                  {false ? (
                    <Icon29Icon
                      className={classNames(projectcss.all, sty.svg___6B4R)}
                      role={"img"}
                    />
                  ) : null}
                </PlasmicLink__>
                <PlasmicLink__
                  className={classNames(
                    projectcss.all,
                    projectcss.a,
                    projectcss.a__tSVYD,
                    sty.link__leLtU
                  )}
                  component={Link}
                  legacyBehavior={false}
                  platform={"nextjs"}
                >
                  {false ? (
                    <Icon29Icon
                      className={classNames(projectcss.all, sty.svg__lFSmS)}
                      role={"img"}
                    />
                  ) : null}
                  <div
                    data-plasmic-name={"contact"}
                    data-plasmic-override={overrides.contact}
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.contact
                    )}
                  >
                    {"Contact Us"}
                  </div>
                  {false ? (
                    <Icon29Icon
                      className={classNames(projectcss.all, sty.svg__qKgCk)}
                      role={"img"}
                    />
                  ) : null}
                </PlasmicLink__>
              </div>
            </div>
          </div>
          <div className={classNames(projectcss.all, sty.freeBox__ddj3P)}>
            <div className={classNames(projectcss.all, sty.freeBox__gkxfv)}>
              <div
                data-plasmic-name={"foreground2"}
                data-plasmic-override={overrides.foreground2}
                className={classNames(projectcss.all, sty.foreground2)}
              >
                <div className={classNames(projectcss.all, sty.freeBox__iQJz)}>
                  <h1
                    data-plasmic-name={"h1"}
                    data-plasmic-override={overrides.h1}
                    className={classNames(
                      projectcss.all,
                      projectcss.h1,
                      projectcss.h1__tSVYD,
                      projectcss.__wab_text,
                      sty.h1
                    )}
                  >
                    {hasVariant(globalVariants, "screen", "mobileOnly")
                      ? "We are the Business and Consulting Expert"
                      : "We help solve problems."}
                  </h1>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__aE7JG
                    )}
                  >
                    {
                      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy"
                    }
                  </div>
                </div>
                <div className={classNames(projectcss.all, sty.freeBox__gyNOo)}>
                  <button
                    className={classNames(
                      projectcss.all,
                      projectcss.button,
                      projectcss.button__tSVYD,
                      sty.button__tGsr
                    )}
                  >
                    {false ? (
                      <Icon29Icon
                        className={classNames(projectcss.all, sty.svg__eeCu5)}
                        role={"img"}
                      />
                    ) : null}
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__d9NXi
                      )}
                    >
                      {"Get IN Touch"}
                    </div>
                    {false ? (
                      <Icon29Icon
                        className={classNames(projectcss.all, sty.svg__yvann)}
                        role={"img"}
                      />
                    ) : null}
                  </button>
                </div>
              </div>
            </div>
          </div>
          <div className={classNames(projectcss.all, sty.freeBox__ubtN)}>
            <div className={classNames(projectcss.all, sty.columns__pqOHv)}>
              <div className={classNames(projectcss.all, sty.column___7DoQq)}>
                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img__bsOap)}
                  displayHeight={
                    hasVariant(globalVariants, "screen", "mobileOnly")
                      ? "237px"
                      : "100%"
                  }
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"100%"}
                  loading={"lazy"}
                  src={{
                    src: "/plasmic/beginners_guide_website_in_3_minutes/images/austinDistelWD1LRb9OeEoUnsplashJpg.jpg",
                    fullWidth: 640,
                    fullHeight: 480,
                    aspectRatio: undefined
                  }}
                />
              </div>
              <div className={classNames(projectcss.all, sty.column__xO3Bh)}>
                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img__kCbLh)}
                  displayHeight={
                    hasVariant(globalVariants, "screen", "mobileOnly")
                      ? "292px"
                      : "100%"
                  }
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"100%"}
                  loading={"lazy"}
                  src={{
                    src: "/plasmic/beginners_guide_website_in_3_minutes/images/brookeCagleUHvRvDr7PgUnsplashJpg.jpg",
                    fullWidth: 3997,
                    fullHeight: 2665,
                    aspectRatio: undefined
                  }}
                />
              </div>
              <div className={classNames(projectcss.all, sty.column__rvtWt)}>
                <div
                  className={classNames(projectcss.all, sty.freeBox___8037S)}
                >
                  <h2
                    className={classNames(
                      projectcss.all,
                      projectcss.h2,
                      projectcss.h2__tSVYD,
                      projectcss.__wab_text,
                      sty.h2__hfR6
                    )}
                  >
                    {hasVariant(globalVariants, "screen", "mobileOnly")
                      ? "About us"
                      : "About us"}
                  </h2>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__em5UT
                    )}
                  >
                    {
                      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages."
                    }
                  </div>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__yflN4)}
                  >
                    <button
                      className={classNames(
                        projectcss.all,
                        projectcss.button,
                        projectcss.button__tSVYD,
                        sty.button___380Mn
                      )}
                    >
                      {false ? (
                        <Icon29Icon
                          className={classNames(projectcss.all, sty.svg__yr1M8)}
                          role={"img"}
                        />
                      ) : null}
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__gu2E
                        )}
                      >
                        {"Read More"}
                      </div>
                      {false ? (
                        <Icon29Icon
                          className={classNames(
                            projectcss.all,
                            sty.svg___6Lfl5
                          )}
                          role={"img"}
                        />
                      ) : null}
                    </button>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div className={classNames(projectcss.all, sty.freeBox__kTid3)}>
            <div className={classNames(projectcss.all, sty.freeBox__pPyZ)}>
              <div className={classNames(projectcss.all, sty.columns__gUhq)}>
                <div className={classNames(projectcss.all, sty.column__hN4Vc)}>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__mdeXe)}
                  >
                    <h2
                      className={classNames(
                        projectcss.all,
                        projectcss.h2,
                        projectcss.h2__tSVYD,
                        projectcss.__wab_text,
                        sty.h2___8Zvv
                      )}
                    >
                      {"Strategize"}
                    </h2>
                    <div
                      className={classNames(projectcss.all, sty.freeBox__ns391)}
                    />

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__lWzLc
                      )}
                    >
                      {
                        "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book."
                      }
                    </div>
                  </div>
                </div>
                <div className={classNames(projectcss.all, sty.column___3Br0L)}>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__fxgP)}
                  >
                    <h2
                      className={classNames(
                        projectcss.all,
                        projectcss.h2,
                        projectcss.h2__tSVYD,
                        projectcss.__wab_text,
                        sty.h2__sCiSw
                      )}
                    >
                      {"Innovate"}
                    </h2>
                    <div
                      className={classNames(projectcss.all, sty.freeBox__vpvqJ)}
                    />

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__pcLr
                      )}
                    >
                      {
                        "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book."
                      }
                    </div>
                  </div>
                </div>
                <div className={classNames(projectcss.all, sty.column__iDy9)}>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__r5CbR)}
                  >
                    <h2
                      className={classNames(
                        projectcss.all,
                        projectcss.h2,
                        projectcss.h2__tSVYD,
                        projectcss.__wab_text,
                        sty.h2__m9NZ4
                      )}
                    >
                      {"Grow"}
                    </h2>
                    <div
                      className={classNames(projectcss.all, sty.freeBox__fz4Hc)}
                    />

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__bt8Mz
                      )}
                    >
                      {
                        "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book."
                      }
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div className={classNames(projectcss.all, sty.freeBox__aP71P)}>
            <div className={classNames(projectcss.all, sty.freeBox__drwpX)}>
              <div className={classNames(projectcss.all, sty.freeBox__oc5S7)}>
                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img__kh7Lv)}
                  displayHeight={"140px"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"none"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"140px"}
                  src={{
                    src: "/plasmic/beginners_guide_website_in_3_minutes/images/imagesJpg.jpg",
                    fullWidth: 225,
                    fullHeight: 225,
                    aspectRatio: undefined
                  }}
                />

                <div className={classNames(projectcss.all, sty.freeBox__n6ZP4)}>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__di5
                    )}
                  >
                    {
                      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book."
                    }
                  </div>
                </div>
                <div className={classNames(projectcss.all, sty.freeBox__lJA)}>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__qrdhw)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.freeBox__m1HDz)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__sOud8
                        )}
                      >
                        {"Lorem Ipsum"}
                      </div>
                    </div>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__coAq
                      )}
                    >
                      {"Director of Sales"}
                    </div>
                  </div>
                </div>
              </div>
              <div className={classNames(projectcss.all, sty.freeBox__kdoyl)}>
                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img__neOrQ)}
                  displayHeight={"140px"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"none"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"140px"}
                  src={{
                    src: "/plasmic/beginners_guide_website_in_3_minutes/images/unnamedJpg.jpg",
                    fullWidth: 370,
                    fullHeight: 411,
                    aspectRatio: undefined
                  }}
                />

                <div className={classNames(projectcss.all, sty.freeBox__wWn63)}>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__twLe2
                    )}
                  >
                    {
                      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book."
                    }
                  </div>
                </div>
                <div
                  className={classNames(projectcss.all, sty.freeBox___9H4WG)}
                >
                  <div
                    className={classNames(projectcss.all, sty.freeBox__amwp6)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.freeBox__bnrNq)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__odLRx
                        )}
                      >
                        {"Lorem Ipsum"}
                      </div>
                    </div>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__txQvi
                      )}
                    >
                      {"Director of Marketing"}
                    </div>
                  </div>
                </div>
              </div>
              <div className={classNames(projectcss.all, sty.freeBox__gu5Sz)}>
                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img__brtjW)}
                  displayHeight={"140px"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"none"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"140px"}
                  src={{
                    src: "/plasmic/beginners_guide_website_in_3_minutes/images/images1Jpg.jpg",
                    fullWidth: 225,
                    fullHeight: 225,
                    aspectRatio: undefined
                  }}
                />

                <div className={classNames(projectcss.all, sty.freeBox__n2JQx)}>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__vzUjJ
                    )}
                  >
                    {
                      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book."
                    }
                  </div>
                </div>
                <div className={classNames(projectcss.all, sty.freeBox__b1PqK)}>
                  <div
                    className={classNames(projectcss.all, sty.freeBox___9LqNu)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.freeBox__hhAz)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__hzHaR
                        )}
                      >
                        {"Lorem Ipsum"}
                      </div>
                    </div>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__vpvZu
                      )}
                    >
                      {"Director of Operations"}
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div className={classNames(projectcss.all, sty.freeBox__xLnDf)}>
            <div className={classNames(projectcss.all, sty.freeBox__cjpma)} />
          </div>
          <div className={classNames(projectcss.all, sty.freeBox__nt7G0)}>
            <div className={classNames(projectcss.all, sty.freeBox__d68Po)}>
              <div
                data-plasmic-name={"foreground3"}
                data-plasmic-override={overrides.foreground3}
                className={classNames(projectcss.all, sty.foreground3)}
              >
                <div className={classNames(projectcss.all, sty.freeBox__vZxcj)}>
                  <h2
                    className={classNames(
                      projectcss.all,
                      projectcss.h2,
                      projectcss.h2__tSVYD,
                      projectcss.__wab_text,
                      sty.h2__yg73
                    )}
                  >
                    {hasVariant(globalVariants, "screen", "mobileOnly")
                      ? "Take your business to the next level"
                      : "Work with us."}
                  </h2>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__jcasr
                    )}
                  >
                    {hasVariant(globalVariants, "screen", "mobileOnly")
                      ? "Rapidiously revolutionize future-proof niches, and authoritatively \nrestore user-centric e-markets."
                      : "Lorem Ipsum is simply dummy text of the printing and typesetting industry. "}
                  </div>
                </div>
                <div className={classNames(projectcss.all, sty.freeBox__k0Yh1)}>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__jb20L)}
                  >
                    <button
                      className={classNames(
                        projectcss.all,
                        projectcss.button,
                        projectcss.button__tSVYD,
                        sty.button___061Jp
                      )}
                    >
                      {false ? (
                        <Icon29Icon
                          className={classNames(projectcss.all, sty.svg__onEkf)}
                          role={"img"}
                        />
                      ) : null}
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__ruCxX
                        )}
                      >
                        {"Get IN Touch"}
                      </div>
                      {false ? (
                        <Icon29Icon
                          className={classNames(projectcss.all, sty.svg__su1JL)}
                          role={"img"}
                        />
                      ) : null}
                    </button>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div className={classNames(projectcss.all, sty.freeBox__fe3Vd)}>
            <div className={classNames(projectcss.all, sty.freeBox__zOgB)}>
              <div
                data-plasmic-name={"rowWrapper"}
                data-plasmic-override={overrides.rowWrapper}
                className={classNames(projectcss.all, sty.rowWrapper)}
              >
                <div
                  data-plasmic-name={"colmn1"}
                  data-plasmic-override={overrides.colmn1}
                  className={classNames(projectcss.all, sty.colmn1)}
                >
                  <h3
                    className={classNames(
                      projectcss.all,
                      projectcss.h3,
                      projectcss.h3__tSVYD,
                      projectcss.__wab_text,
                      sty.h3__wm5Y0
                    )}
                  >
                    {"About us"}
                  </h3>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___6KUsp
                    )}
                  >
                    <React.Fragment>
                      <React.Fragment>
                        {
                          "\u00a9 Company. All rights reserved. This site proudly built with "
                        }
                      </React.Fragment>
                      {
                        <PlasmicLink__
                          className={classNames(
                            projectcss.all,
                            projectcss.a,
                            projectcss.a__tSVYD,
                            projectcss.__wab_text,
                            projectcss.plasmic_default__inline,
                            sty.link__q0VMu
                          )}
                          component={Link}
                          href={"https://www.plasmic.app"}
                          legacyBehavior={false}
                          platform={"nextjs"}
                        >
                          {"Plasmic"}
                        </PlasmicLink__>
                      }
                      <React.Fragment>{"."}</React.Fragment>
                    </React.Fragment>
                  </div>
                </div>
                <div
                  data-plasmic-name={"colmn2"}
                  data-plasmic-override={overrides.colmn2}
                  className={classNames(projectcss.all, sty.colmn2)}
                >
                  <h3
                    className={classNames(
                      projectcss.all,
                      projectcss.h3,
                      projectcss.h3__tSVYD,
                      projectcss.__wab_text,
                      sty.h3__xOmMi
                    )}
                  >
                    {"Links"}
                  </h3>
                  <PlasmicLink__
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      projectcss.a__tSVYD,
                      projectcss.__wab_text,
                      sty.link__jkSUh
                    )}
                    component={Link}
                    legacyBehavior={false}
                    platform={"nextjs"}
                  >
                    {"Services"}
                  </PlasmicLink__>
                  <PlasmicLink__
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      projectcss.a__tSVYD,
                      projectcss.__wab_text,
                      sty.link__nDzx4
                    )}
                    component={Link}
                    legacyBehavior={false}
                    platform={"nextjs"}
                  >
                    {"About us"}
                  </PlasmicLink__>
                  <PlasmicLink__
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      projectcss.a__tSVYD,
                      projectcss.__wab_text,
                      sty.link__hyknj
                    )}
                    component={Link}
                    href={"#"}
                    legacyBehavior={false}
                    platform={"nextjs"}
                  >
                    {"Testimonials"}
                  </PlasmicLink__>
                  <PlasmicLink__
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      projectcss.a__tSVYD,
                      projectcss.__wab_text,
                      sty.link___6USb
                    )}
                    component={Link}
                    href={"#"}
                    legacyBehavior={false}
                    platform={"nextjs"}
                  >
                    {"Blog"}
                  </PlasmicLink__>
                  <PlasmicLink__
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      projectcss.a__tSVYD,
                      projectcss.__wab_text,
                      sty.link__b20Lb
                    )}
                    component={Link}
                    legacyBehavior={false}
                    platform={"nextjs"}
                  >
                    {"Contact us\n"}
                  </PlasmicLink__>
                </div>
                <div
                  data-plasmic-name={"colmn22"}
                  data-plasmic-override={overrides.colmn22}
                  className={classNames(projectcss.all, sty.colmn22)}
                >
                  <h3
                    className={classNames(
                      projectcss.all,
                      projectcss.h3,
                      projectcss.h3__tSVYD,
                      projectcss.__wab_text,
                      sty.h3__mBuw8
                    )}
                  >
                    {"Nav Links"}
                  </h3>
                  <PlasmicLink__
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      projectcss.a__tSVYD,
                      projectcss.__wab_text,
                      sty.link__grmQ
                    )}
                    component={Link}
                    legacyBehavior={false}
                    platform={"nextjs"}
                  >
                    {"Services"}
                  </PlasmicLink__>
                  <PlasmicLink__
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      projectcss.a__tSVYD,
                      projectcss.__wab_text,
                      sty.link__lago7
                    )}
                    component={Link}
                    legacyBehavior={false}
                    platform={"nextjs"}
                  >
                    {"About us"}
                  </PlasmicLink__>
                  <PlasmicLink__
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      projectcss.a__tSVYD,
                      projectcss.__wab_text,
                      sty.link__qlJyv
                    )}
                    component={Link}
                    legacyBehavior={false}
                    platform={"nextjs"}
                  >
                    {"Testimonials"}
                  </PlasmicLink__>
                  <PlasmicLink__
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      projectcss.a__tSVYD,
                      projectcss.__wab_text,
                      sty.link__cPerg
                    )}
                    component={Link}
                    href={"#"}
                    legacyBehavior={false}
                    platform={"nextjs"}
                  >
                    {"Blog"}
                  </PlasmicLink__>
                  <PlasmicLink__
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      projectcss.a__tSVYD,
                      projectcss.__wab_text,
                      sty.link__riY1U
                    )}
                    component={Link}
                    legacyBehavior={false}
                    platform={"nextjs"}
                  >
                    {"Contact us\n"}
                  </PlasmicLink__>
                </div>
                <div
                  data-plasmic-name={"colmn3"}
                  data-plasmic-override={overrides.colmn3}
                  className={classNames(projectcss.all, sty.colmn3)}
                >
                  <h3
                    className={classNames(
                      projectcss.all,
                      projectcss.h3,
                      projectcss.h3__tSVYD,
                      projectcss.__wab_text,
                      sty.h3___0KCmY
                    )}
                  >
                    {"Contact "}
                  </h3>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__o8Ot
                    )}
                  >
                    {"1234 Lorem Ipsum .\nLorem Ipsum , GA 30308"}
                  </div>
                  <PlasmicLink__
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      projectcss.a__tSVYD,
                      projectcss.__wab_text,
                      sty.link___59VgO
                    )}
                    component={Link}
                    href={"#"}
                    legacyBehavior={false}
                    platform={"nextjs"}
                  >
                    {"xyz@company.com"}
                  </PlasmicLink__>
                  <PlasmicLink__
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      projectcss.a__tSVYD,
                      projectcss.__wab_text,
                      sty.link__sVpDu
                    )}
                    component={Link}
                    href={"#"}
                    legacyBehavior={false}
                    platform={"nextjs"}
                  >
                    {"1234567890"}
                  </PlasmicLink__>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: [
    "root",
    "aboutUs",
    "contact",
    "foreground2",
    "h1",
    "foreground3",
    "rowWrapper",
    "colmn1",
    "colmn2",
    "colmn22",
    "colmn3"
  ],
  aboutUs: ["aboutUs"],
  contact: ["contact"],
  foreground2: ["foreground2", "h1"],
  h1: ["h1"],
  foreground3: ["foreground3"],
  rowWrapper: ["rowWrapper", "colmn1", "colmn2", "colmn22", "colmn3"],
  colmn1: ["colmn1"],
  colmn2: ["colmn2"],
  colmn22: ["colmn22"],
  colmn3: ["colmn3"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  aboutUs: "a";
  contact: "div";
  foreground2: "div";
  h1: "h1";
  foreground3: "div";
  rowWrapper: "div";
  colmn1: "div";
  colmn2: "div";
  colmn22: "div";
  colmn3: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicHome__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicHome__VariantsArgs;
    args?: PlasmicHome__ArgsType;
    overrides?: NodeOverridesType<T>;
  } &
    // Specify variants directly as props
    Omit<PlasmicHome__VariantsArgs, ReservedPropsType> &
    // Specify args directly as props
    Omit<PlasmicHome__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicHome__ArgProps,
          internalVariantPropNames: PlasmicHome__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicHome__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicHome";
  } else {
    func.displayName = `PlasmicHome.${nodeName}`;
  }
  return func;
}

export const PlasmicHome = Object.assign(
  // Top-level PlasmicHome renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    aboutUs: makeNodeComponent("aboutUs"),
    contact: makeNodeComponent("contact"),
    foreground2: makeNodeComponent("foreground2"),
    h1: makeNodeComponent("h1"),
    foreground3: makeNodeComponent("foreground3"),
    rowWrapper: makeNodeComponent("rowWrapper"),
    colmn1: makeNodeComponent("colmn1"),
    colmn2: makeNodeComponent("colmn2"),
    colmn22: makeNodeComponent("colmn22"),
    colmn3: makeNodeComponent("colmn3"),

    // Metadata about props expected for PlasmicHome
    internalVariantProps: PlasmicHome__VariantProps,
    internalArgProps: PlasmicHome__ArgProps,

    pageMetadata: generateDynamicMetadata(wrapQueriesWithLoadingProxy({}), {
      pageRoute: "/home",
      pagePath: "/home",
      params: {},
      query: {}
    })
  }
);

export default PlasmicHome;
/* prettier-ignore-end */
